import { Folder as FolderType } from "@/redux/slice/foldersSlice";

export const foldersDummyData: FolderType[] = [
  {
    id: "1",
    subject: "Restaurant Launching Brochure",
    description: "Brochure for the grand opening of our new restaurant.",
    created_date: "01/01/2025",
    last_modified: "15/01/2025",
    file_count: 5,
    is_selected: false,
  },
  {
    id: "2",
    subject: "Marketing Plan 2025",
    description: "Detailed marketing plan for the year 2025.",
    created_date: "10/01/2025",
    last_modified: "20/01/2025",
    file_count: 3,
    is_selected: false,
  },
  {
    id: "3",
    subject: "Quarterly Financial Report Q1",
    description: "Financial performance report for the first quarter of 2025.",
    created_date: "01/02/2025",
    last_modified: "15/02/2025",
    file_count: 7,
    is_selected: false,
  },
  {
    id: "4",
    subject: "Employee Handbook Update",
    description: "Updated version of the employee handbook for 2025.",
    created_date: "05/01/2025",
    last_modified: "12/01/2025",
    file_count: 2,
    is_selected: false,
  },
  {
    id: "5",
    subject: "Project Proposal - Green Energy",
    description: "Proposal document for the Green Energy project initiative.",
    created_date: "01/03/2025",
    last_modified: "10/03/2025",
    file_count: 6,
    is_selected: false,
  },
  {
    id: "6",
    subject: "Client Onboarding Checklist",
    description: "Checklist for onboarding new clients effectively.",
    created_date: "15/01/2025",
    last_modified: "01/02/2025",
    file_count: 4,
    is_selected: false,
  },
  {
    id: "7",
    subject: "Team Building Event 2025",
    description: "Details for the annual team-building event.",
    created_date: "05/04/2025",
    last_modified: "12/04/2025",
    file_count: 8,
    is_selected: false,
  },
  {
    id: "8",
    subject: "Product Roadmap 2025",
    description: "Strategic roadmap for product development in 2025.",
    created_date: "20/01/2025",
    last_modified: "05/02/2025",
    file_count: 5,
    is_selected: false,
  },
  {
    id: "9",
    subject: "Annual Performance Reviews",
    description: "Performance review records for all employees.",
    created_date: "10/02/2025",
    last_modified: "01/03/2025",
    file_count: 10,
    is_selected: false,
  },
  {
    id: "10",
    subject: "Training Material - Sales Team",
    description: "Training modules for the sales team.",
    created_date: "25/01/2025",
    last_modified: "15/02/2025",
    file_count: 9,
    is_selected: false,
  },
];
