import { Folder as FolderType } from "@/redux/slice/foldersSlice";

export const foldersDummyData: FolderType[] = [
  {
    id: "1",
    subject: "Restaurant Launching Brochure",
    description: "Brochure for the grand opening of our new restaurant.",
    created_date: "01/01/2025",
    last_modified: "15/01/2025",
    file_count: 5,
    is_selected: false,
    files: [
      {
        id: "f1",
        file_name: "menu.pdf",
        upload_date: "02/01/2025",
        size_kb: 500,
        mime_type: "application/pdf",
      },
      {
        id: "f2",
        file_name: "flyer.png",
        upload_date: "03/01/2025",
        size_kb: 1200,
        mime_type: "image/png",
      },
      {
        id: "f3",
        file_name: "social_media_ad.mp4",
        upload_date: "04/01/2025",
        size_kb: 5000,
        mime_type: "video/mp4",
      },
      {
        id: "f4",
        file_name: "logo.jpg",
        upload_date: "05/01/2025",
        size_kb: 800,
        mime_type: "image/jpeg",
      },
      {
        id: "f5",
        file_name: "brochure.pdf",
        upload_date: "06/01/2025",
        size_kb: 2500,
        mime_type: "application/pdf",
      },
    ],
  },
  {
    id: "2",
    subject: "Marketing Reports",
    description: "Quarterly marketing reports and analysis.",
    created_date: "10/02/2025",
    last_modified: "18/02/2025",
    file_count: 3,
    is_selected: false,
    files: [
      {
        id: "f6",
        file_name: "Q1_report.pdf",
        upload_date: "11/02/2025",
        size_kb: 900,
        mime_type: "application/pdf",
      },
      {
        id: "f7",
        file_name: "Q2_report.pdf",
        upload_date: "12/02/2025",
        size_kb: 1100,
        mime_type: "application/pdf",
      },
      {
        id: "f8",
        file_name: "annual_summary.docx",
        upload_date: "13/02/2025",
        size_kb: 500,
        mime_type:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    ],
  },
  {
    id: "3",
    subject: "Employee Training Materials",
    description: "Documents for employee training sessions.",
    created_date: "05/03/2025",
    last_modified: "12/03/2025",
    file_count: 4,
    is_selected: false,
    files: [
      {
        id: "f9",
        file_name: "safety_guidelines.pdf",
        upload_date: "06/03/2025",
        size_kb: 1200,
        mime_type: "application/pdf",
      },
      {
        id: "f10",
        file_name: "presentation.pptx",
        upload_date: "07/03/2025",
        size_kb: 2500,
        mime_type:
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      },
      {
        id: "f11",
        file_name: "attendance_list.xlsx",
        upload_date: "08/03/2025",
        size_kb: 600,
        mime_type:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      },
      {
        id: "f12",
        file_name: "training_videos.mp4",
        upload_date: "09/03/2025",
        size_kb: 10000,
        mime_type: "video/mp4",
      },
    ],
  },
  {
    id: "4",
    subject: "Financial Statements",
    description: "Annual financial reports and balance sheets.",
    created_date: "20/03/2025",
    last_modified: "25/03/2025",
    file_count: 2,
    is_selected: false,
    files: [
      {
        id: "f13",
        file_name: "balance_sheet_2025.xlsx",
        upload_date: "21/03/2025",
        size_kb: 1500,
        mime_type:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      },
      {
        id: "f14",
        file_name: "profit_loss_statement.pdf",
        upload_date: "22/03/2025",
        size_kb: 1300,
        mime_type: "application/pdf",
      },
    ],
  },
  {
    id: "5",
    subject: "Client Contracts",
    description: "Signed contracts and agreements with clients.",
    created_date: "01/04/2025",
    last_modified: "10/04/2025",
    file_count: 3,
    is_selected: false,
    files: [
      {
        id: "f15",
        file_name: "client_A_contract.pdf",
        upload_date: "02/04/2025",
        size_kb: 800,
        mime_type: "application/pdf",
      },
      {
        id: "f16",
        file_name: "client_B_contract.pdf",
        upload_date: "03/04/2025",
        size_kb: 900,
        mime_type: "application/pdf",
      },
      {
        id: "f17",
        file_name: "nda_agreement.pdf",
        upload_date: "04/04/2025",
        size_kb: 700,
        mime_type: "application/pdf",
      },
    ],
  },
  {
    id: "6",
    subject: "Product Design Files",
    description: "Blueprints and design files for new products.",
    created_date: "15/04/2025",
    last_modified: "22/04/2025",
    file_count: 2,
    is_selected: false,
    files: [
      {
        id: "f18",
        file_name: "product_render.psd",
        upload_date: "16/04/2025",
        size_kb: 5000,
        mime_type: "image/vnd.adobe.photoshop",
      },
      {
        id: "f19",
        file_name: "3d_model.stl",
        upload_date: "17/04/2025",
        size_kb: 3200,
        mime_type: "model/stl",
      },
    ],
  },
  {
    id: "7",
    subject: "Meeting Minutes",
    description: "Minutes from team and board meetings.",
    created_date: "01/05/2025",
    last_modified: "05/05/2025",
    file_count: 3,
    is_selected: false,
    files: [
      {
        id: "f20",
        file_name: "team_meeting.docx",
        upload_date: "02/05/2025",
        size_kb: 400,
        mime_type:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
      {
        id: "f21",
        file_name: "board_meeting.pdf",
        upload_date: "03/05/2025",
        size_kb: 600,
        mime_type: "application/pdf",
      },
      {
        id: "f22",
        file_name: "stakeholder_meeting.docx",
        upload_date: "04/05/2025",
        size_kb: 450,
        mime_type:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    ],
  },
  {
    id: "8",
    subject: "Legal Documents",
    description: "Important legal and compliance documents.",
    created_date: "08/05/2025",
    last_modified: "15/05/2025",
    file_count: 2,
    is_selected: false,
    files: [
      {
        id: "f23",
        file_name: "company_bylaws.pdf",
        upload_date: "09/05/2025",
        size_kb: 1700,
        mime_type: "application/pdf",
      },
      {
        id: "f24",
        file_name: "privacy_policy.docx",
        upload_date: "10/05/2025",
        size_kb: 700,
        mime_type:
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      },
    ],
  },
  {
    id: "9",
    subject: "Technology Conference 2025",
    description: "Documents and presentations for the annual tech conference.",
    created_date: "10/04/2025",
    last_modified: "20/04/2025",
    file_count: 4,
    is_selected: false,
    files: [
      {
        id: "f28",
        file_name: "agenda.pdf",
        upload_date: "11/04/2025",
        size_kb: 700,
        mime_type: "application/pdf",
      },
      {
        id: "f29",
        file_name: "keynote.pptx",
        upload_date: "12/04/2025",
        size_kb: 1500,
        mime_type:
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
      },
      {
        id: "f30",
        file_name: "attendee_list.xlsx",
        upload_date: "13/04/2025",
        size_kb: 400,
        mime_type:
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      },
      {
        id: "f31",
        file_name: "event_promo.mp4",
        upload_date: "14/04/2025",
        size_kb: 4500,
        mime_type: "video/mp4",
      },
    ],
  },
  // {
  //   id: "10",
  //   subject: "Company Rebranding",
  //   description: "Assets related to the company's rebranding campaign.",
  //   created_date: "25/05/2025",
  //   last_modified: "30/05/2025",
  //   file_count: 5,
  //   is_selected: false,
  //   files: [
  //     {
  //       id: "f32",
  //       file_name: "new_logo.png",
  //       upload_date: "26/05/2025",
  //       size_kb: 1200,
  //       mime_type: "image/png",
  //     },
  //     {
  //       id: "f33",
  //       file_name: "brand_guidelines.pdf",
  //       upload_date: "27/05/2025",
  //       size_kb: 2300,
  //       mime_type: "application/pdf",
  //     },
  //     {
  //       id: "f34",
  //       file_name: "social_media_banners.zip",
  //       upload_date: "28/05/2025",
  //       size_kb: 5000,
  //       mime_type: "application/zip",
  //     },
  //     {
  //       id: "f35",
  //       file_name: "business_card_design.ai",
  //       upload_date: "29/05/2025",
  //       size_kb: 1500,
  //       mime_type: "application/postscript",
  //     },
  //     {
  //       id: "f36",
  //       file_name: "website_mockups.psd",
  //       upload_date: "30/05/2025",
  //       size_kb: 3200,
  //       mime_type: "image/vnd.adobe.photoshop",
  //     },
  //   ],
  // },
];
